In [1]:
import sys
#lets you access python's runtime environment
from pathlib import Path
#sys.path is a built in variable in the sys module and contains a list of directories that is seached through when you do an import
#so we are appending the src directory to that
sys.path.append(str(Path().resolve().parent / "src"))
import config

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score

panel_data_path = config.PROJECT_ROOT/ "data" / "panel_data.csv"
panel_data = pd.read_csv(panel_data_path)

Train/test split must be time-aware. Entries in the train set should all predate entries in the test set.

In [2]:
year_counts = panel_data.groupby('Year').size().reset_index(name = 'NumberOfRows')
year_counts = year_counts.sort_values('Year')
year_counts['Cumulative'] = year_counts['NumberOfRows'].cumsum()
total_rows = year_counts.loc[len(year_counts)-1, 'Cumulative']
year_counts['EntriesPrecedingAndIncluding(%)'] = (year_counts['Cumulative']/total_rows) *100
year_counts

   Year  NumberOfRows  Cumulative  EntriesPrecedingAndIncluding(%)
0  2015         20521       20521                         6.723501
1  2016         26591       47112                        15.435778
2  2017         31939       79051                        25.900273
3  2018         37641      116692                        38.232972
4  2019         40916      157608                        51.638692
5  2020         17673      175281                        57.429074
6  2021         25873      201154                        65.906105
7  2022         27153      228307                        74.802515
8  2023         35947      264254                        86.580192
9  2024         40959      305213                       100.000000

Could take entries from 2023 and before for train set for approximately 87/13 train/test split.

In [3]:


panel = panel_data.drop(columns = ['Name', 'WeightClassKg', 'Sex'])
train = panel[panel['Year']<=2023].copy()
test = panel[panel['Year']>2023].copy()

train_X = train.drop(columns = 'CompetesNextYear')
train_y = train['CompetesNextYear']
test_X = test.drop(columns = 'CompetesNextYear')
test_y = test['CompetesNextYear']



clf = RandomForestClassifier()
clf.fit(train_X, train_y)

RandomForestClassifier()

In [4]:

preds = clf.predict(test_X)

acc = accuracy_score(test_y,preds)
f1 = f1_score(test_y, preds)

In [5]:
panel_data.groupby('CompetesNextYear').size().reset_index(name = 'Number')

   CompetesNextYear  Number
0             False  180574
1              True  124639

In [6]:
competes_multiple = panel_data.groupby('Name').size().reset_index(name = 'YearsCompeted')

In [7]:
print(acc)
print(f1)

0.6228667692082326
0.6027312707352828

In [8]:
len(panel_data[panel_data['NumberOfMeets']>1])/len(panel_data)

0.34208569097646563

In [9]:
panel

,Year,Age,TimeCompetingYearEnd,NumberOfMeets,Goodlift,Dots,Wilks,BestMeetOfYear,AverageAttemptsMade,MostAttemptsMade,LeastAttemptsMade,LastMeetAttemptsMade,MeetsSinceLastBombOut,NumberOfBombOuts,PercentageImprovement,CompetesNextYear,WeightClassKgCode,F,M,Mx
0,2017,16.5,27,1,61.15,300.75,295.29,300.0,8.0,8,8,8,999,0,NaN,False,0.714286,1,0,0
1,2019,17.5,91,1,36.81,181.55,180.52,250.0,7.0,7,7,7,999,0,NaN,False,0.375000,0,1,0
2,2022,22.5,143,1,76.21,386.08,388.02,480.0,7.0,7,7,7,999,0,NaN,False,0.250000,0,1,0
3,2019,16.0,96,1,45.30,221.93,219.95,317.5,7.0,7,7,7,999,0,NaN,False,0.500000,0,1,0
4,2016,27.5,89,1,NaN,NaN,NaN,NaN,0.0,0,0,0,0,1,NaN,False,0.375000,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305208,2024,NaN,276,1,75.72,369.43,365.36,545.0,6.0,6,6,6,999,0,NaN,False,0.500000,0,1,0
305209,2024,NaN,276,1,62.03,302.67,306.93,262.5,6.0,6,6,6,999,0,NaN,False,0.375000,1,0,0
305210,2024,NaN,276,1,55.06,268.19,272.53,230.0,3.0,3,3,3,999,0,NaN,False,0.375000,1,0,0
305211,2024,NaN,276,1,46.00,225.19,227.26,200.0,4.0,4,4,4,999,0,NaN,False,0.500000,1,0,0
305212,2024,35.5,276,1,62.13,303.64,300.97,505.0,8.0,8,8,8,999,0,NaN,False,0.875000,0,1,0

In [10]:
importances = clf.feature_importances_

feature_importance_df = pd.DataFrame({
    'Feature': train_X.columns,
    'Importance': importances
}).sort_values('Importance', ascending=False, ignore_index =True)

print(feature_importance_df)

                  Feature    Importance
0    TimeCompetingYearEnd  1.400086e-01
1                   Wilks  1.148440e-01
2                Goodlift  1.145689e-01
3                    Dots  1.141414e-01
4                     Age  1.133591e-01
5          BestMeetOfYear  1.002426e-01
6                    Year  6.861247e-02
7   PercentageImprovement  6.229579e-02
8       WeightClassKgCode  4.659025e-02
9           NumberOfMeets  3.103759e-02
10    AverageAttemptsMade  2.342231e-02
11      LeastAttemptsMade  1.848891e-02
12   LastMeetAttemptsMade  1.826936e-02
13       MostAttemptsMade  1.751416e-02
14  MeetsSinceLastBombOut  4.752377e-03
15                      F  4.188111e-03
16                      M  4.011654e-03
17       NumberOfBombOuts  3.652147e-03
18                     Mx  3.563177e-07